CREATE TABLE IF NOT EXISTS amazon_listing (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键编号',
    tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '租户编号',
    shop_id BIGINT NOT NULL COMMENT '关联 amazon_shop.id',
    sku VARCHAR(100) NOT NULL COMMENT 'Amazon Seller SKU',
    m_sku VARCHAR(100) NULL COMMENT 'ERP 主 SKU',
    marketplace_id VARCHAR(64) NOT NULL COMMENT 'Amazon Marketplace ID',
    asin VARCHAR(20) NULL COMMENT 'Amazon 标准识别号',
    product_type VARCHAR(100) NULL COMMENT 'Amazon 商品类型',
    condition_type VARCHAR(50) NULL COMMENT '商品状况类型',
    item_name VARCHAR(1000) NULL COMMENT 'Amazon 商品名称',
    amazon_created_time DATETIME(3) NULL COMMENT 'Amazon Listing 创建时间',
    amazon_updated_time DATETIME(3) NULL COMMENT 'Amazon Listing 更新时间',
    statuses JSON NOT NULL COMMENT 'Amazon Listing 状态列表',
    images JSON NOT NULL COMMENT 'Amazon Listing 图片列表',
    attributes JSON NOT NULL COMMENT 'Amazon Listing 动态属性',
    issues JSON NOT NULL COMMENT 'Amazon Listing 校验问题列表',
    first_sync_time DATETIME NULL COMMENT '首次同步时间',
    last_sync_time DATETIME NULL COMMENT '最后同步时间',
    creator VARCHAR(64) NULL DEFAULT '' COMMENT '创建者',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updater VARCHAR(64) NULL DEFAULT '' COMMENT '更新者',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted BIT NOT NULL DEFAULT b'0' COMMENT '是否删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_amazon_listing_tenant_shop_sku_marketplace (tenant_id, shop_id, sku, marketplace_id),
    KEY idx_amazon_listing_tenant_shop (tenant_id, shop_id),
    KEY idx_amazon_listing_tenant_m_sku (tenant_id, m_sku),
    KEY idx_amazon_listing_tenant_marketplace_asin (tenant_id, marketplace_id, asin),
    CONSTRAINT fk_amazon_listing_shop FOREIGN KEY (shop_id) REFERENCES amazon_shop (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Amazon Listing 主表';
