### Order Management 订单管理接口测试

@temuAccessToken = uplv3hfyt5kcwoymrgnajnbl1ow5qxlz4sqhev6hl3xosz5dejrtyl2jre7
@shopId = 1
@regionId = 211
@parentOrderSn = PO-211-18671748222072338
@orderSn = 211-08979834258470637

### 查询订单列表
POST {{baseUrl}}/temu/order-management/orders/list
Content-Type: application/json
Authorization: Bearer {{token}}
tenant-id: {{adminTenantId}}

{
  "shopId": {{shopId}},
  "site": "US",
  "accessToken": "{{temuAccessToken}}",
  "parentOrderStatus": 4,
  "regionId": {{regionId}},
  "pageNumber": 1,
  "pageSize": 5
}

### 查询本地订单列表
GET {{baseUrl}}/temu/order-management/orders/page?shopId={{shopId}}&pageNo=1&pageSize=10
Authorization: Bearer {{token}}
tenant-id: {{adminTenantId}}

### 查询父订单详情
POST {{baseUrl}}/temu/order-management/orders/detail
Content-Type: application/json
Authorization: Bearer {{token}}
tenant-id: {{adminTenantId}}

{
  "shopId": {{shopId}},
  "site": "US",
  "accessToken": "{{temuAccessToken}}",
  "parentOrderSn": "{{parentOrderSn}}"
}

### 查询定制订单详情
POST {{baseUrl}}/temu/order-management/orders/customization/detail
Content-Type: application/json
Authorization: Bearer {{token}}
tenant-id: {{adminTenantId}}

{
  "shopId": {{shopId}},
  "site": "US",
  "accessToken": "{{temuAccessToken}}",
  "orderSnList": ["{{orderSn}}"]
}

### 查询订单收货信息
POST {{baseUrl}}/temu/order-management/orders/shipping-info
Content-Type: application/json
Authorization: Bearer {{token}}
tenant-id: {{adminTenantId}}

{
  "shopId": {{shopId}},
  "site": "US",
  "accessToken": "{{temuAccessToken}}",
  "parentOrderSn": "{{parentOrderSn}}"
}

### 查询订单承运商列表
POST {{baseUrl}}/temu/order-management/shipping-companies/list
Content-Type: application/json
Authorization: Bearer {{token}}
tenant-id: {{adminTenantId}}

{
  "shopId": {{shopId}},
  "site": "US",
  "accessToken": "{{temuAccessToken}}",
  "regionId": "{{regionId}}"
}
