### 查询销售伙伴补货指标
POST {{baseUrl}}/amazon/replenishment/selling-partner-metrics/search
Authorization: Bearer {{token}}
Content-Type: application/json
tenant-id: {{adminTenantId}}

{"shopId":1,"countryCode":"US","body":{"marketplaceId":"ATVPDKIKX0DER","timeInterval":{"startTime":"2026-08-01T00:00:00Z","endTime":"2026-08-08T00:00:00Z"}}}

### 查询报价补货指标
POST {{baseUrl}}/amazon/replenishment/offer-metrics/search
Authorization: Bearer {{token}}
Content-Type: application/json
tenant-id: {{adminTenantId}}

{"shopId":1,"countryCode":"US","body":{"marketplaceId":"ATVPDKIKX0DER","timeInterval":{"startTime":"2026-08-01T00:00:00Z","endTime":"2026-08-08T00:00:00Z"}}}

### 查询补货报价
POST {{baseUrl}}/amazon/replenishment/offers/search
Authorization: Bearer {{token}}
Content-Type: application/json
tenant-id: {{adminTenantId}}

{"shopId":1,"countryCode":"US","body":{"marketplaceId":"ATVPDKIKX0DER"}}
