CREATE TABLE IF NOT EXISTS temu_api_request_log (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键编号',
    tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '租户编号',
    request_id VARCHAR(64) NOT NULL COMMENT '本次调用唯一请求编号',
    trace_id VARCHAR(64) NULL COMMENT '链路追踪编号',
    shop_id BIGINT NULL COMMENT 'Temu 店铺编号',
    site VARCHAR(16) NULL COMMENT 'Temu 站点代码，例如 US、DE、JP',
    api_category VARCHAR(64) NOT NULL COMMENT 'API 分类，例如 product、order',
    operation_name VARCHAR(128) NOT NULL COMMENT 'Temu OpenAPI 接口 type',
    request_method VARCHAR(10) NOT NULL COMMENT 'HTTP 请求方式',
    request_url VARCHAR(2048) NULL COMMENT '脱敏后的完整请求 URL',
    request_path VARCHAR(512) NULL COMMENT '请求路径',
    file_id BIGINT NULL COMMENT '响应归档文件编号，对应 infra_file.id',
    request_params JSON NULL COMMENT '脱敏后的查询参数或请求体',
    request_headers JSON NULL COMMENT '脱敏后的请求头',
    request_body_hash CHAR(64) NULL COMMENT '原始请求体 SHA-256',
    http_status_code INT NULL COMMENT 'HTTP 状态码；网络异常时为空',
    result_status TINYINT NOT NULL DEFAULT 0 COMMENT '调用结果：0-处理中，1-成功，2-失败',
    error_code VARCHAR(128) NULL COMMENT 'Temu 或应用错误码',
    error_message VARCHAR(1000) NULL COMMENT '脱敏后的错误信息',
    temu_request_id VARCHAR(128) NULL COMMENT 'Temu 返回的请求编号',
    rate_limit VARCHAR(64) NULL COMMENT 'Temu 返回的速率限制',
    retry_count INT NOT NULL DEFAULT 0 COMMENT '本次调用已重试次数',
    duration_ms INT NULL COMMENT '请求总耗时，单位毫秒',
    requested_at DATETIME NOT NULL COMMENT '开始请求时间',
    completed_at DATETIME NULL COMMENT '请求完成时间',
    creator VARCHAR(64) NULL DEFAULT '' COMMENT '创建者',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updater VARCHAR(64) NULL DEFAULT '' COMMENT '更新者',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',
    deleted BIT NOT NULL DEFAULT b'0' COMMENT '是否删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_temu_api_request_log_tenant_request (tenant_id, request_id),
    KEY idx_temu_api_request_log_tenant_shop_time (tenant_id, shop_id, requested_at),
    KEY idx_temu_api_request_log_tenant_operation_time (tenant_id, operation_name, requested_at),
    KEY idx_temu_api_request_log_temu_request_id (temu_request_id),
    KEY idx_temu_api_request_log_tenant_result_time (tenant_id, result_status, requested_at),
    KEY idx_temu_api_request_log_file_id (file_id),
    KEY idx_temu_api_request_log_tenant_id (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Temu OpenAPI 请求调用日志';
