CREATE TABLE IF NOT EXISTS temu_order_shipping_info (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键编号',
    shop_id BIGINT NOT NULL COMMENT '关联 temu_shop.id',
    parent_order_sn VARCHAR(64) NOT NULL COMMENT 'Temu 父订单号',
    receipt_name VARCHAR(256) NULL COMMENT '收件人姓名',
    receipt_additional_name VARCHAR(256) NULL COMMENT '附加收件人姓名',
    first_name VARCHAR(128) NULL COMMENT '收件人名字',
    last_name VARCHAR(128) NULL COMMENT '收件人姓氏',
    additional_first_name VARCHAR(128) NULL COMMENT '附加收件人名字',
    additional_last_name VARCHAR(128) NULL COMMENT '附加收件人姓氏',
    mail VARCHAR(320) NULL COMMENT '收件邮箱',
    mobile VARCHAR(64) NULL COMMENT '收件手机号',
    backup_mobile VARCHAR(64) NULL COMMENT '备用手机号',
    region_name_1 VARCHAR(128) NULL COMMENT '一级行政区名称，例如国家',
    region_name_2 VARCHAR(128) NULL COMMENT '二级行政区名称，例如州省',
    region_name_3 VARCHAR(128) NULL COMMENT '三级行政区名称，例如城市',
    region_name_4 VARCHAR(128) NULL COMMENT '四级行政区名称',
    post_code VARCHAR(32) NULL COMMENT '邮政编码',
    address_line_1 VARCHAR(512) NULL COMMENT '地址第一行',
    address_line_2 VARCHAR(512) NULL COMMENT '地址第二行',
    address_line_3 VARCHAR(512) NULL COMMENT '地址第三行',
    address_line_all VARCHAR(1536) NULL COMMENT '完整收货地址',
    warning VARCHAR(1024) NULL COMMENT 'Temu 地址警告信息',
    last_sync_time DATETIME NOT NULL COMMENT '最近从 Temu 同步时间',
    creator VARCHAR(64) NULL DEFAULT '' COMMENT '创建者',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updater VARCHAR(64) NULL DEFAULT '' COMMENT '更新者',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted BIT NOT NULL DEFAULT b'0' COMMENT '是否删除',
    tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '租户编号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_temu_order_shipping_info_tenant_shop_parent (tenant_id, shop_id, parent_order_sn),
    KEY idx_temu_order_shipping_info_tenant_id (tenant_id),
    KEY idx_temu_order_shipping_info_tenant_shop_sync (tenant_id, shop_id, last_sync_time),
    CONSTRAINT fk_temu_order_shipping_info_shop FOREIGN KEY (shop_id) REFERENCES temu_shop (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Temu 父订单收货信息表';
