CREATE TABLE IF NOT EXISTS temu_order_detail (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键编号',
    shop_id BIGINT NOT NULL COMMENT '关联 temu_shop.id',
    parent_order_sn VARCHAR(64) NOT NULL COMMENT 'Temu 父订单号',
    parent_order_status INT NULL COMMENT '父订单状态',
    region_name_1 VARCHAR(128) NULL COMMENT '父订单地址一级行政区名称',
    region_name_2 VARCHAR(128) NULL COMMENT '父订单地址二级行政区名称',
    region_name_3 VARCHAR(128) NULL COMMENT '父订单地址三级行政区名称',
    site_id BIGINT NULL COMMENT 'Temu 站点编号',
    region_id BIGINT NULL COMMENT 'Temu 区域编号',
    order_payment_type VARCHAR(16) NULL COMMENT '父订单支付类型',
    shipping_method INT NULL COMMENT '配送方式',
    shipment_consolidated_by_main_mall BIT NULL COMMENT '是否由主商城合单发货',
    has_shipping_fee BIT NULL COMMENT '用户是否支付零运费',
    parent_order_time DATETIME NULL COMMENT '父订单创建时间',
    expect_ship_latest_time DATETIME NULL COMMENT '最晚发货时间',
    parent_order_pending_finish_time DATETIME NULL COMMENT '待处理完成时间',
    latest_delivery_time DATETIME NULL COMMENT '最晚送达时间',
    parent_shipping_time DATETIME NULL COMMENT '父订单发货时间',
    parent_confirm_time DATETIME NULL COMMENT '父订单确认时间',
    parent_order_labels JSON NULL COMMENT '父订单标签 JSON',
    fulfillment_warnings JSON NULL COMMENT '父订单履约提醒 JSON',
    batch_order_number_list JSON NULL COMMENT '协作仓批次订单号 JSON',
    order_list JSON NOT NULL COMMENT 'Temu 原始子订单详情 JSON',
    last_sync_time DATETIME NOT NULL COMMENT '最近从 Temu 同步时间',
    creator VARCHAR(64) NULL DEFAULT '' COMMENT '创建者',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updater VARCHAR(64) NULL DEFAULT '' COMMENT '更新者',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted BIT NOT NULL DEFAULT b'0' COMMENT '是否删除',
    tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '租户编号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_temu_order_detail_tenant_shop_parent (tenant_id, shop_id, parent_order_sn),
    KEY idx_temu_order_detail_tenant_id (tenant_id),
    KEY idx_temu_order_detail_tenant_shop_sync (tenant_id, shop_id, last_sync_time),
    CONSTRAINT fk_temu_order_detail_shop FOREIGN KEY (shop_id) REFERENCES temu_shop (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Temu 父订单详情表';
