CREATE TABLE IF NOT EXISTS temu_seller (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键编号',
    shop_id BIGINT NOT NULL COMMENT '关联 temu_shop.id',
    semi_unique_id VARCHAR(128) NULL COMMENT 'Temu semiUniqueId',
    region_id INT NULL COMMENT 'Temu 区域编号',
    mall_id BIGINT NOT NULL COMMENT 'Temu mallId',
    mall_type INT NULL COMMENT 'Temu mallType',
    tags JSON NULL COMMENT 'Temu 店铺标签枚举列表',
    app_subscribe_status TINYINT NULL COMMENT '应用订阅状态',
    expired_time BIGINT NULL COMMENT '授权过期时间，Unix 时间戳（秒）',
    expired_at DATETIME NULL COMMENT '授权过期时间，便于数据库查询',
    app_subscribe_event_code_list JSON NULL COMMENT '应用订阅事件编码列表',
    auth_event_code_list JSON NULL COMMENT '授权事件及权限状态列表',
    api_scope_list JSON NULL COMMENT 'API 权限范围列表',
    response_json JSON NULL COMMENT '接口完整响应快照，便于兼容后续字段',
    last_sync_time DATETIME NULL COMMENT '最近一次同步授权信息时间',
    creator VARCHAR(64) NULL DEFAULT '' COMMENT '创建者',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updater VARCHAR(64) NULL DEFAULT '' COMMENT '更新者',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted BIT NOT NULL DEFAULT b'0' COMMENT '是否删除',
    tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '租户编号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_temu_seller_tenant_shop (tenant_id, shop_id),
    KEY idx_temu_seller_shop_id (shop_id),
    KEY idx_temu_seller_mall_id (mall_id),
    KEY idx_temu_seller_tenant_id (tenant_id),
    CONSTRAINT fk_temu_seller_shop FOREIGN KEY (shop_id) REFERENCES temu_shop (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Temu 卖家商城授权信息表';
