CREATE TABLE IF NOT EXISTS temu_order (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键编号',
    shop_id BIGINT NOT NULL COMMENT '关联 temu_shop.id',
    seller_id BIGINT NOT NULL COMMENT '关联 temu_seller.id，由店铺授权关系确定',
    parent_order_sn VARCHAR(64) NOT NULL COMMENT 'Temu 父订单号',
    order_sn VARCHAR(64) NOT NULL COMMENT 'Temu 子订单号',
    site_id INT NULL COMMENT 'Temu 站点编号',
    region_id BIGINT NULL COMMENT 'Temu 区域编号',
    parent_order_status INT NULL COMMENT '父订单状态',
    order_status INT NULL COMMENT '子订单状态',
    parent_order_payment_type VARCHAR(32) NULL COMMENT '父订单支付类型',
    order_payment_type VARCHAR(32) NULL COMMENT '子订单支付类型',
    fulfillment_type VARCHAR(64) NULL COMMENT '履约方式',
    goods_id BIGINT NULL COMMENT 'Temu 商品编号',
    sku_id BIGINT NULL COMMENT 'Temu SKU 编号',
    goods_name VARCHAR(512) NULL COMMENT '商品名称',
    original_goods_name VARCHAR(512) NULL COMMENT '原始商品名称',
    spec VARCHAR(1024) NULL COMMENT '商品规格',
    original_spec_name VARCHAR(1024) NULL COMMENT '原始商品规格',
    thumb_url VARCHAR(2048) NULL COMMENT '商品缩略图',
    quantity INT NULL COMMENT '下单数量',
    canceled_quantity_before_shipment INT NULL COMMENT '发货前取消数量',
    original_order_quantity INT NULL COMMENT '原始下单数量',
    shipping_method INT NULL COMMENT '父订单发货方式',
    shipment_consolidated_by_main_mall BIT NULL COMMENT '是否由主商城合单发货',
    has_shipping_fee BIT NULL COMMENT '是否含运费',
    parent_order_time DATETIME NULL COMMENT '父订单创建时间',
    parent_confirm_time DATETIME NULL COMMENT '父订单确认时间',
    order_create_time DATETIME NULL COMMENT '子订单创建时间',
    order_shipping_time DATETIME NULL COMMENT '要求发货时间',
    expect_ship_latest_time DATETIME NULL COMMENT '最晚预计发货时间',
    latest_delivery_time DATETIME NULL COMMENT '最晚送达时间',
    temu_update_time DATETIME NULL COMMENT 'Temu 订单最后更新时间',
    parent_order_labels JSON NULL COMMENT '父订单标签 JSON',
    order_labels JSON NULL COMMENT '子订单标签 JSON',
    parent_fulfillment_warnings JSON NULL COMMENT '父订单履约预警 JSON',
    fulfillment_warnings JSON NULL COMMENT '子订单履约预警 JSON',
    package_abnormal_types JSON NULL COMMENT '包裹异常类型 JSON',
    product_list JSON NULL COMMENT '商品映射列表 JSON',
    last_sync_time DATETIME NULL COMMENT '最近同步时间',
    creator VARCHAR(64) NULL DEFAULT '' COMMENT '创建者',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updater VARCHAR(64) NULL DEFAULT '' COMMENT '更新者',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted BIT NOT NULL DEFAULT b'0' COMMENT '是否删除',
    tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '租户编号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_temu_order_tenant_shop_sn (tenant_id, shop_id, order_sn),
    KEY idx_temu_order_tenant_id (tenant_id),
    KEY idx_temu_order_tenant_seller_create (tenant_id, seller_id, order_create_time),
    KEY idx_temu_order_tenant_shop_parent (tenant_id, shop_id, parent_order_sn),
    KEY idx_temu_order_tenant_shop_status (tenant_id, shop_id, parent_order_status, order_status),
    CONSTRAINT fk_temu_order_shop FOREIGN KEY (shop_id) REFERENCES temu_shop (id),
    CONSTRAINT fk_temu_order_seller FOREIGN KEY (seller_id) REFERENCES temu_seller (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Temu 子订单表';
