CREATE TABLE IF NOT EXISTS temu_goods_category (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键编号',
    site VARCHAR(16) NOT NULL COMMENT 'Temu 站点代码，例如 US、DE、JP',
    cat_id BIGINT NOT NULL COMMENT 'Temu 类目编号',
    parent_cat_id BIGINT NOT NULL DEFAULT 0 COMMENT 'Temu 父类目编号，一级类目为 0',
    level INT NOT NULL COMMENT '类目层级，从 1 开始',
    cat_name VARCHAR(256) NOT NULL COMMENT 'Temu 类目名称',
    available_status TINYINT NOT NULL COMMENT 'Temu 类目可用状态',
    second_hand_category BIT NOT NULL DEFAULT b'0' COMMENT '是否为二手商品类目',
    cat_type INT NULL COMMENT 'Temu 类目类型',
    expand_cat_type INT NULL COMMENT 'Temu 扩展类目类型',
    leaf BIT NOT NULL DEFAULT b'0' COMMENT '是否为叶子类目',
    last_sync_time DATETIME NOT NULL COMMENT '最近一次从 Temu 同步的时间',
    creator VARCHAR(64) NULL DEFAULT '' COMMENT '创建者',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updater VARCHAR(64) NULL DEFAULT '' COMMENT '更新者',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted BIT NOT NULL DEFAULT b'0' COMMENT '是否删除',
    tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '租户编号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_temu_goods_category_tenant_site_cat (tenant_id, site, cat_id),
    KEY idx_temu_goods_category_tenant_parent (tenant_id, site, parent_cat_id),
    KEY idx_temu_goods_category_tenant_name (tenant_id, site, cat_name),
    KEY idx_temu_goods_category_tenant_id (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Temu 商品类目表';
