CREATE TABLE IF NOT EXISTS temu_shop (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键编号',
    shop_type TINYINT NOT NULL COMMENT '店铺类型：1-全托管，2-半托管，3-本土店铺',
    site VARCHAR(16) NOT NULL COMMENT 'Temu 站点代码，例如 US、DE、JP',
    shop_name VARCHAR(128) NOT NULL COMMENT '店铺名称',
    auth_token VARCHAR(512) NOT NULL COMMENT 'Temu 授权 Token',
    status TINYINT NOT NULL DEFAULT 0 COMMENT '状态：0-开启，1-关闭，对应系统 common_status 字典',
    semi_unique_id VARCHAR(128) NULL COMMENT 'Temu semiUniqueId',
    region_id INT NULL COMMENT 'Temu 区域编号',
    mall_id BIGINT NULL COMMENT 'Temu mallId',
    mall_type INT NULL COMMENT 'Temu mallType',
    tags JSON NULL COMMENT 'Temu 店铺标签枚举列表',
    app_subscribe_status TINYINT NULL COMMENT '应用订阅状态',
    expired_time BIGINT NULL COMMENT '授权过期时间，Unix 时间戳（秒）',
    expired_at DATETIME NULL COMMENT '授权过期时间，便于数据库查询',
    app_subscribe_event_code_list JSON NULL COMMENT '应用订阅事件编码列表',
    auth_event_code_list JSON NULL COMMENT '授权事件及权限状态列表',
    api_scope_list JSON NULL COMMENT 'API 权限范围列表',
    response_json JSON NULL COMMENT '接口完整响应快照',
    last_sync_time DATETIME NULL COMMENT '最近一次同步授权信息时间',
    authorize_time DATETIME NULL COMMENT '授权时间',
    authorize_expire_time DATETIME NULL COMMENT '授权过期时间',
    creator VARCHAR(64) NULL DEFAULT '' COMMENT '创建者',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updater VARCHAR(64) NULL DEFAULT '' COMMENT '更新者',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted BIT NOT NULL DEFAULT b'0' COMMENT '是否删除',
    tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '租户编号',
    PRIMARY KEY (id),
    KEY idx_temu_shop_tenant_id (tenant_id),
    KEY idx_temu_shop_site (site)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Temu 店铺表';
