CREATE TABLE IF NOT EXISTS amazon_seller_account (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键编号',
    tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '租户编号',
    shop_id BIGINT NOT NULL COMMENT '关联 amazon_shop.id',
    business_type VARCHAR(64) NULL COMMENT 'Amazon 企业类型，例如 PRIVATE_LIMITED',
    selling_plan VARCHAR(64) NULL COMMENT 'Amazon 销售计划，例如 PROFESSIONAL',
    primary_contact_name VARCHAR(256) NULL COMMENT '主要联系人拉丁名称',
    primary_contact_non_latin_name VARCHAR(256) NULL COMMENT '主要联系人非拉丁名称',
    primary_contact_address_line1 VARCHAR(512) NULL COMMENT '主要联系人地址第一行',
    primary_contact_address_line2 VARCHAR(512) NULL COMMENT '主要联系人地址第二行',
    primary_contact_country_code VARCHAR(8) NULL COMMENT '主要联系人地址国家代码',
    primary_contact_state_or_province_code VARCHAR(64) NULL COMMENT '主要联系人地址省州代码',
    primary_contact_city VARCHAR(128) NULL COMMENT '主要联系人地址城市',
    primary_contact_postal_code VARCHAR(32) NULL COMMENT '主要联系人地址邮编',
    business_name VARCHAR(512) NULL COMMENT '企业拉丁名称',
    business_non_latin_name VARCHAR(512) NULL COMMENT '企业非拉丁名称',
    registered_address_line1 VARCHAR(512) NULL COMMENT '企业注册地址第一行',
    registered_address_line2 VARCHAR(512) NULL COMMENT '企业注册地址第二行',
    registered_country_code VARCHAR(8) NULL COMMENT '企业注册地址国家代码',
    registered_state_or_province_code VARCHAR(64) NULL COMMENT '企业注册地址省州代码',
    registered_city VARCHAR(128) NULL COMMENT '企业注册地址城市',
    registered_postal_code VARCHAR(32) NULL COMMENT '企业注册地址邮编',
    company_registration_number VARCHAR(128) NULL COMMENT '企业注册号',
    company_tax_identification_number VARCHAR(128) NULL COMMENT '企业税务识别号',
    response_json JSON NULL COMMENT 'Sellers Account 接口完整响应快照，用于兼容后续字段',
    last_sync_time DATETIME NOT NULL COMMENT '最近一次从 Amazon 同步账户信息的时间',
    creator VARCHAR(64) NULL DEFAULT '' COMMENT '创建者',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updater VARCHAR(64) NULL DEFAULT '' COMMENT '更新者',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted BIT NOT NULL DEFAULT b'0' COMMENT '是否删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_amazon_seller_account_tenant_shop (tenant_id, shop_id),
    KEY idx_amazon_seller_account_tenant_sync_time (tenant_id, last_sync_time),
    KEY idx_amazon_seller_account_tenant_id (tenant_id),
    CONSTRAINT fk_amazon_seller_account_shop FOREIGN KEY (shop_id) REFERENCES amazon_shop (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Amazon 卖家账户及企业档案表';
