CREATE TABLE IF NOT EXISTS amazon_report_request (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键编号',
    tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '租户编号',
    request_no VARCHAR(64) NOT NULL COMMENT '本地报表请求唯一编号，用于任务幂等与关联日志',
    shop_id BIGINT NOT NULL COMMENT '关联 amazon_shop.id',
    country_code VARCHAR(8) NOT NULL COMMENT '请求站点国家代码，例如 US',
    marketplace_ids JSON NOT NULL COMMENT 'Amazon Marketplace ID 列表，Reports API 最多支持 25 个',
    report_type VARCHAR(128) NOT NULL COMMENT 'Amazon 报表类型，例如 GET_MERCHANT_LISTINGS_ALL_DATA',
    report_options JSON NULL COMMENT '报表附加选项，随报表类型变化',
    data_start_time DATETIME(3) NULL COMMENT '报表数据开始时间',
    data_end_time DATETIME(3) NULL COMMENT '报表数据结束时间',

    amazon_report_id VARCHAR(128) NULL COMMENT 'Amazon reportId；在店铺维度唯一',
    amazon_report_schedule_id VARCHAR(128) NULL COMMENT '创建该报表的 Amazon 计划编号；手工请求为空',
    amazon_processing_status VARCHAR(32) NULL COMMENT 'Amazon 状态：IN_QUEUE、IN_PROGRESS、DONE、CANCELLED、FATAL',
    amazon_created_time DATETIME(3) NULL COMMENT 'Amazon 创建报表时间',
    processing_start_time DATETIME(3) NULL COMMENT 'Amazon 开始处理时间',
    processing_end_time DATETIME(3) NULL COMMENT 'Amazon 完成处理时间',

    report_document_id VARCHAR(128) NULL COMMENT 'Amazon reportDocumentId',
    compression_algorithm VARCHAR(32) NULL COMMENT '下载文件压缩算法，例如 GZIP',
    file_id BIGINT NULL COMMENT '已下载并归档的文件编号，对应 infra_file.id',
    download_time DATETIME(3) NULL COMMENT '报表文件下载完成时间',

    task_status TINYINT NOT NULL DEFAULT 0 COMMENT '任务状态：0-待提交，1-等待Amazon处理，2-待下载，3-成功，4-重试等待，5-失败，6-已取消',
    execute_stage TINYINT NOT NULL DEFAULT 0 COMMENT '当前执行阶段：0-提交，1-查询状态，2-下载文件',
    retry_count INT NOT NULL DEFAULT 0 COMMENT '当前阶段已重试次数',
    max_retry_count INT NOT NULL DEFAULT 5 COMMENT '当前阶段最大重试次数',
    next_retry_time DATETIME(3) NULL COMMENT '下次可执行时间；用于退避重试和轮询调度',
    last_request_time DATETIME(3) NULL COMMENT '最近一次调用 Amazon 时间',
    last_error_code VARCHAR(128) NULL COMMENT '最近一次失败错误码',
    last_error_message VARCHAR(1000) NULL COMMENT '最近一次失败原因',
    completed_time DATETIME(3) NULL COMMENT '任务成功、失败或取消的最终完成时间',

    lock_version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本，防止多个任务执行器重复处理',
    lock_expire_time DATETIME(3) NULL COMMENT '任务执行租约到期时间；超时后允许其他执行器接管',

    creator VARCHAR(64) NULL DEFAULT '' COMMENT '创建者',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updater VARCHAR(64) NULL DEFAULT '' COMMENT '更新者',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted BIT NOT NULL DEFAULT b'0' COMMENT '是否删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_amazon_report_request_tenant_no (tenant_id, request_no),
    UNIQUE KEY uk_amazon_report_request_tenant_shop_report (tenant_id, shop_id, amazon_report_id),
    KEY idx_amazon_report_request_dispatch (tenant_id, task_status, next_retry_time),
    KEY idx_amazon_report_request_tenant_shop_type_time (tenant_id, shop_id, report_type, create_time),
    KEY idx_amazon_report_request_tenant_report_status (tenant_id, amazon_processing_status),
    KEY idx_amazon_report_request_tenant_id (tenant_id),
    CONSTRAINT fk_amazon_report_request_shop FOREIGN KEY (shop_id) REFERENCES amazon_shop (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Amazon 报表请求及异步处理任务表';
