CREATE TABLE IF NOT EXISTS amazon_order (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键编号',
    tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '租户编号',
    shop_id BIGINT NOT NULL COMMENT '关联 amazon_shop.id',
    amazon_order_id VARCHAR(64) NOT NULL COMMENT 'Amazon 订单编号',
    marketplace_id VARCHAR(64) NULL COMMENT 'Amazon Marketplace ID',
    purchase_date DATETIME(3) NULL COMMENT '买家下单时间',
    last_update_date DATETIME(3) NULL COMMENT 'Amazon 最后更新时间',
    order_status VARCHAR(32) NULL COMMENT '订单状态',
    fulfillment_channel VARCHAR(8) NULL COMMENT '履约渠道：AFN 或 MFN',
    number_of_items_shipped INT NULL COMMENT '已发货商品数量',
    number_of_items_unshipped INT NULL COMMENT '未发货商品数量',
    payment_method VARCHAR(32) NULL COMMENT '支付方式',
    shipment_service_level_category VARCHAR(64) NULL COMMENT '配送服务级别分类',
    order_type VARCHAR(64) NULL COMMENT '订单类型',
    earliest_ship_date DATETIME(3) NULL COMMENT '最早发货时间',
    latest_ship_date DATETIME(3) NULL COMMENT '最晚发货时间',
    is_business_order BIT NULL COMMENT '是否为企业订单',
    is_prime BIT NULL COMMENT '是否为 Prime 订单',
    is_access_point_order BIT NULL COMMENT '是否为自提点订单',
    is_global_express_enabled BIT NULL COMMENT '是否启用全球快递',
    is_premium_order BIT NULL COMMENT '是否为高级配送订单',
    is_sold_by_ab BIT NULL COMMENT '是否由 Amazon Business 销售',
    is_iba BIT NULL COMMENT '是否为 IBA 订单',
    payment_method_details JSON NULL COMMENT '支付方式明细数组 JSON',
    shipping_address JSON NULL COMMENT '收货地址对象 JSON',
    buyer_info JSON NULL COMMENT '买家信息对象 JSON',
    last_sync_time DATETIME(3) NULL COMMENT '最近同步时间',
    creator VARCHAR(64) NULL DEFAULT '' COMMENT '创建者',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updater VARCHAR(64) NULL DEFAULT '' COMMENT '更新者',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',
    deleted BIT NOT NULL DEFAULT b'0' COMMENT '是否删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_amazon_order_tenant_shop_order (tenant_id, shop_id, amazon_order_id),
    KEY idx_amazon_order_tenant_id (tenant_id),
    KEY idx_amazon_order_tenant_shop_purchase (tenant_id, shop_id, purchase_date),
    KEY idx_amazon_order_tenant_shop_status (tenant_id, shop_id, order_status),
    KEY idx_amazon_order_tenant_marketplace (tenant_id, marketplace_id),
    CONSTRAINT fk_amazon_order_shop FOREIGN KEY (shop_id) REFERENCES amazon_shop (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Amazon 订单表';
