### Add Products 商品发布接口测试

@temuAccessToken = replace-with-temu-access-token

### 查询 Temu 商品分类
POST {{baseUrl}}/temu/add-products/categories
Content-Type: application/json
Authorization: Bearer {{token}}
tenant-id: {{adminTenantId}}

{
  "site": "US",
  "accessToken": "{{temuAccessToken}}",
  "language": "en",
  "parentCatId": 1
}
