package cn.iocoder.yudao.module.amazon.controller.admin.services;
import cn.iocoder.yudao.framework.common.pojo.CommonResult; import cn.iocoder.yudao.module.amazon.controller.admin.services.vo.ServicesReqVO; import cn.iocoder.yudao.module.amazon.service.services.ServicesService; import jakarta.annotation.Resource; import jakarta.validation.Valid; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.web.bind.annotation.*; import java.util.Map;
/** Amazon Services 管理接口。 */
@RestController @RequestMapping("/amazon/services") public class ServicesController {
 @Resource private ServicesService service;
 /** 查询服务工单。 */ @PostMapping("/jobs/get") @PreAuthorize("@ss.hasPermission('amazon:services:query')") public CommonResult<Map<String,Object>> getJob(@Valid @RequestBody ServicesReqVO r){return CommonResult.success(service.getServiceJobByServiceJobId(r));}
 /** 取消服务工单。 */ @PostMapping("/jobs/cancel") @PreAuthorize("@ss.hasPermission('amazon:services:update')") public CommonResult<Map<String,Object>> cancelJob(@Valid @RequestBody ServicesReqVO r){return CommonResult.success(service.cancelServiceJobByServiceJobId(r));}
 /** 完成服务工单。 */ @PostMapping("/jobs/complete") @PreAuthorize("@ss.hasPermission('amazon:services:update')") public CommonResult<Map<String,Object>> completeJob(@Valid @RequestBody ServicesReqVO r){return CommonResult.success(service.completeServiceJobByServiceJobId(r));}
 /** 查询服务工单列表。 */ @PostMapping("/jobs/list") @PreAuthorize("@ss.hasPermission('amazon:services:query')") public CommonResult<Map<String,Object>> jobs(@Valid @RequestBody ServicesReqVO r){return CommonResult.success(service.getServiceJobs(r));}
 /** 创建服务预约。 */ @PostMapping("/appointments/create") @PreAuthorize("@ss.hasPermission('amazon:services:update')") public CommonResult<Map<String,Object>> createAppointment(@Valid @RequestBody ServicesReqVO r){return CommonResult.success(service.addAppointmentForServiceJobByServiceJobId(r));}
 /** 改约服务预约。 */ @PostMapping("/appointments/reschedule") @PreAuthorize("@ss.hasPermission('amazon:services:update')") public CommonResult<Map<String,Object>> reschedule(@Valid @RequestBody ServicesReqVO r){return CommonResult.success(service.rescheduleAppointmentForServiceJobByServiceJobId(r));}
 /** 分配预约资源。 */ @PostMapping("/appointments/resources/assign") @PreAuthorize("@ss.hasPermission('amazon:services:update')") public CommonResult<Map<String,Object>> resources(@Valid @RequestBody ServicesReqVO r){return CommonResult.success(service.assignAppointmentResources(r));}
 /** 设置预约履约数据。 */ @PostMapping("/appointments/fulfillment/set") @PreAuthorize("@ss.hasPermission('amazon:services:update')") public CommonResult<Map<String,Object>> fulfillment(@Valid @RequestBody ServicesReqVO r){return CommonResult.success(service.setAppointmentFulfillmentData(r));}
 /** 查询范围时段容量。 */ @PostMapping("/resources/capacity/range") @PreAuthorize("@ss.hasPermission('amazon:services:query')") public CommonResult<Map<String,Object>> range(@Valid @RequestBody ServicesReqVO r){return CommonResult.success(service.getRangeSlotCapacity(r));}
 /** 查询固定时段容量。 */ @PostMapping("/resources/capacity/fixed") @PreAuthorize("@ss.hasPermission('amazon:services:query')") public CommonResult<Map<String,Object>> fixed(@Valid @RequestBody ServicesReqVO r){return CommonResult.success(service.getFixedSlotCapacity(r));}
 /** 更新资源日程。 */ @PostMapping("/resources/schedule/update") @PreAuthorize("@ss.hasPermission('amazon:services:update')") public CommonResult<Map<String,Object>> schedule(@Valid @RequestBody ServicesReqVO r){return CommonResult.success(service.updateSchedule(r));}
 /** 创建预约预留。 */ @PostMapping("/reservations/create") @PreAuthorize("@ss.hasPermission('amazon:services:update')") public CommonResult<Map<String,Object>> createReservation(@Valid @RequestBody ServicesReqVO r){return CommonResult.success(service.createReservation(r));}
 /** 更新预约预留。 */ @PostMapping("/reservations/update") @PreAuthorize("@ss.hasPermission('amazon:services:update')") public CommonResult<Map<String,Object>> updateReservation(@Valid @RequestBody ServicesReqVO r){return CommonResult.success(service.updateReservation(r));}
 /** 取消预约预留。 */ @PostMapping("/reservations/cancel") @PreAuthorize("@ss.hasPermission('amazon:services:update')") public CommonResult<Map<String,Object>> cancelReservation(@Valid @RequestBody ServicesReqVO r){return CommonResult.success(service.cancelReservation(r));}
 /** 查询工单预约时段。 */ @PostMapping("/appointments/slots/by-job") @PreAuthorize("@ss.hasPermission('amazon:services:query')") public CommonResult<Map<String,Object>> jobSlots(@Valid @RequestBody ServicesReqVO r){return CommonResult.success(service.getAppointmmentSlotsByJobId(r));}
 /** 查询通用预约时段。 */ @PostMapping("/appointments/slots") @PreAuthorize("@ss.hasPermission('amazon:services:query')") public CommonResult<Map<String,Object>> slots(@Valid @RequestBody ServicesReqVO r){return CommonResult.success(service.getAppointmentSlots(r));}
 /** 创建服务文档上传地址。 */ @PostMapping("/documents/upload-destination/create") @PreAuthorize("@ss.hasPermission('amazon:services:update')") public CommonResult<Map<String,Object>> document(@Valid @RequestBody ServicesReqVO r){return CommonResult.success(service.createServiceDocumentUploadDestination(r));}
}
