CREATE TABLE IF NOT EXISTS amazon_shop (
    id BIGINT NOT NULL COMMENT '主键编号',
    seller_id VARCHAR(64) NULL COMMENT 'Amazon sellerId',
    marketplace_id VARCHAR(64) NULL COMMENT '默认 marketplaceId',
    shop_name VARCHAR(128) NOT NULL COMMENT '店铺名称',
    region VARCHAR(32) NOT NULL DEFAULT 'NA' COMMENT 'Amazon 区域：NA、EU、FE',
    authorize_time DATETIME NULL COMMENT '授权时间',
    authorize_expire_time DATETIME NULL COMMENT '授权过期时间',
    seller_refresh_token VARCHAR(2048) NULL COMMENT 'Seller refresh token',
    seller_access_token VARCHAR(4096) NULL COMMENT 'Seller access token，短期缓存',
    seller_access_token_expires_at DATETIME NULL COMMENT 'Seller access token 过期时间',
    ad_refresh_token VARCHAR(2048) NULL COMMENT '广告 refresh token',
    ad_access_token VARCHAR(4096) NULL COMMENT '广告 access token，短期缓存',
    ad_access_token_expires_at DATETIME NULL COMMENT '广告 access token 过期时间',
    ad_authorize_time DATETIME NULL COMMENT '广告授权时间',
    ad_authorize_expire_time DATETIME NULL COMMENT '广告授权过期时间',
    status TINYINT NOT NULL DEFAULT 0 COMMENT '状态：0-启用，1-禁用',
    creator VARCHAR(64) NULL DEFAULT '' COMMENT '创建者',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updater VARCHAR(64) NULL DEFAULT '' COMMENT '更新者',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted BIT NOT NULL DEFAULT b'0' COMMENT '是否删除',
    tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '租户编号',
    PRIMARY KEY (id),
    KEY idx_amazon_shop_tenant_id (tenant_id),
    KEY idx_amazon_shop_seller_id (seller_id),
    KEY idx_amazon_shop_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Amazon 多店铺授权表';
