### 查询卖家站点参与状态
POST {{baseUrl}}/amazon/sellers/marketplace-participations
Authorization: Bearer {{token}}
Content-Type: application/json
tenant-id: {{adminTenantId}}

{"shopId": 1}

### 同步卖家账户及站点参与状态
POST {{baseUrl}}/amazon/sellers/account/sync
Authorization: Bearer {{token}}
Content-Type: application/json
tenant-id: {{adminTenantId}}

{"shopId": 1}

### 查询卖家账户
POST {{baseUrl}}/amazon/sellers/account
Authorization: Bearer {{token}}
Content-Type: application/json
tenant-id: {{adminTenantId}}

{"shopId": 2}
