### 使用授权码获取 Amazon Token（不会保存店铺授权信息）
POST {{baseUrl}}/amazon/auth/test-token
Authorization: Bearer {{token}}
Content-Type: application/json
tenant-id: {{adminTenantId}}

{
  "code": "{{amazonAuthorizationCode}}",
  "countryCode": "US"
}

### 使用 refresh token 刷新 Amazon Token（不会保存店铺授权信息）
POST {{baseUrl}}/amazon/auth/refresh-token
Authorization: Bearer {{token}}
Content-Type: application/json
tenant-id: {{adminTenantId}}

{
  "refreshToken": "Atzr|IwEBIPYe-W2nrNF1R336LFEoO_Rbv_bYb743OAIEzjiHt51kxRvj4XqUd9lKOdlStwJ5LEF-zGsQHNdS8n0MA4HyYVye0MSVH-R25FYnVKgHTlW6SxH55EeQltu5xdVoYDcrQoUbNcAxX2VEmww2S2Y8Tl9dN7JkOhW7aiPbHTwdmvmB3CYtZShegmNTfbudgobYjjB3lhPQP_tpDFioJ_NvhPJKLWvubwRmwfZaZlGvijigdQIOjDP2bME4XPFTdKOQiplCGbTp00fqEVPubpQAOFM6QSXGTBIA-jN5pYRFj-yueY9-tpIk9m_KTDVSbF_eQEc",
  "countryCode": "US"
}

### 获取 Amazon Seller access token
GET {{baseUrl}}/amazon/auth/seller-token?shopId=2
Authorization: Bearer {{token}}
tenant-id: {{adminTenantId}}
