package cn.iocoder.yudao.module.amazon.controller.admin.shipping;

import cn.iocoder.yudao.framework.common.pojo.CommonResult;
import cn.iocoder.yudao.module.amazon.controller.admin.shipping.vo.ShippingRequestVO;
import cn.iocoder.yudao.module.amazon.service.shipping.ShippingService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.Resource;
import jakarta.validation.Valid;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import java.util.Map;

/** Amazon Shipping V1/V2 管理接口。 */
@Tag(name = "管理后台 - Amazon Shipping") @RestController @RequestMapping("/amazon/shipping") @Validated
public class ShippingController {
    @Resource private ShippingService shippingService;
    /** 创建 Shipping V1 货件。 */ @PostMapping("/v1/shipments") @Operation(summary = "创建 Shipping V1 货件") @PreAuthorize("@ss.hasPermission('amazon:shipping:create')") public CommonResult<Map<String, Object>> createShipmentV1(@Valid @RequestBody ShippingRequestVO r) { return call(r, "createShipment", "POST", "/shipping/v1/shipments"); }
    /** 查询 Shipping V1 货件。 */ @PostMapping("/v1/shipments/detail") @Operation(summary = "查询 Shipping V1 货件") @PreAuthorize("@ss.hasPermission('amazon:shipping:query')") public CommonResult<Map<String, Object>> getShipmentV1(@Valid @RequestBody ShippingRequestVO r) { return call(r, "getShipment", "GET", "/shipping/v1/shipments/{id}"); }
    /** 取消 Shipping V1 货件。 */ @PostMapping("/v1/shipments/cancel") @Operation(summary = "取消 Shipping V1 货件") @PreAuthorize("@ss.hasPermission('amazon:shipping:update')") public CommonResult<Map<String, Object>> cancelShipmentV1(@Valid @RequestBody ShippingRequestVO r) { return call(r, "cancelShipment", "POST", "/shipping/v1/shipments/{id}/cancel"); }
    /** 购买 Shipping V1 标签。 */ @PostMapping("/v1/shipments/purchase-labels") @Operation(summary = "购买 Shipping V1 标签") @PreAuthorize("@ss.hasPermission('amazon:shipping:create')") public CommonResult<Map<String, Object>> purchaseLabelsV1(@Valid @RequestBody ShippingRequestVO r) { return call(r, "purchaseLabels", "POST", "/shipping/v1/shipments/{id}/purchaseLabels"); }
    /** 获取 Shipping V1 运单标签。 */ @PostMapping("/v1/shipments/label") @Operation(summary = "获取 Shipping V1 运单标签") @PreAuthorize("@ss.hasPermission('amazon:shipping:query')") public CommonResult<Map<String, Object>> retrieveShippingLabelV1(@Valid @RequestBody ShippingRequestVO r) { return call(r, "retrieveShippingLabel", "POST", "/shipping/v1/shipments/{id}/containers/{secondaryId}/label"); }
    /** 直接购买 Shipping V1 货件。 */ @PostMapping("/v1/purchase-shipment") @Operation(summary = "直接购买 Shipping V1 货件") @PreAuthorize("@ss.hasPermission('amazon:shipping:create')") public CommonResult<Map<String, Object>> purchaseShipmentV1(@Valid @RequestBody ShippingRequestVO r) { return call(r, "purchaseShipment", "POST", "/shipping/v1/purchaseShipment"); }
    /** 查询 Shipping V1 费率。 */ @PostMapping("/v1/rates") @Operation(summary = "查询 Shipping V1 费率") @PreAuthorize("@ss.hasPermission('amazon:shipping:query')") public CommonResult<Map<String, Object>> getRatesV1(@Valid @RequestBody ShippingRequestVO r) { return call(r, "getRates", "POST", "/shipping/v1/rates"); }
    /** 查询 Shipping V1 账户。 */ @PostMapping("/v1/account") @Operation(summary = "查询 Shipping V1 账户") @PreAuthorize("@ss.hasPermission('amazon:shipping:query')") public CommonResult<Map<String, Object>> getAccountV1(@Valid @RequestBody ShippingRequestVO r) { return call(r, "getAccount", "GET", "/shipping/v1/account"); }
    /** 查询 Shipping V1 物流轨迹。 */ @PostMapping("/v1/tracking") @Operation(summary = "查询 Shipping V1 物流轨迹") @PreAuthorize("@ss.hasPermission('amazon:shipping:query')") public CommonResult<Map<String, Object>> getTrackingV1(@Valid @RequestBody ShippingRequestVO r) { return call(r, "getTrackingInformation", "GET", "/shipping/v1/tracking/{id}"); }

    /** 查询 Shipping V2 费率。 */ @PostMapping("/v2/rates") @Operation(summary = "查询 Shipping V2 费率") @PreAuthorize("@ss.hasPermission('amazon:shipping:query')") public CommonResult<Map<String, Object>> getRatesV2(@Valid @RequestBody ShippingRequestVO r) { return call(r, "getRates", "POST", "/shipping/v2/shipments/rates"); }
    /** 直接购买 Shipping V2 货件。 */ @PostMapping("/v2/shipments/direct-purchase") @Operation(summary = "直接购买 Shipping V2 货件") @PreAuthorize("@ss.hasPermission('amazon:shipping:create')") public CommonResult<Map<String, Object>> directPurchaseShipment(@Valid @RequestBody ShippingRequestVO r) { return call(r, "directPurchaseShipment", "POST", "/shipping/v2/shipments/directPurchase"); }
    /** 购买 Shipping V2 货件。 */ @PostMapping("/v2/shipments") @Operation(summary = "购买 Shipping V2 货件") @PreAuthorize("@ss.hasPermission('amazon:shipping:create')") public CommonResult<Map<String, Object>> purchaseShipmentV2(@Valid @RequestBody ShippingRequestVO r) { return call(r, "purchaseShipment", "POST", "/shipping/v2/shipments"); }
    /** 一键购买 Shipping V2 货件。 */ @PostMapping("/v2/one-click-shipment") @Operation(summary = "一键购买 Shipping V2 货件") @PreAuthorize("@ss.hasPermission('amazon:shipping:create')") public CommonResult<Map<String, Object>> oneClickShipment(@Valid @RequestBody ShippingRequestVO r) { return call(r, "oneClickShipment", "POST", "/shipping/v2/oneClickShipment"); }
    /** 查询 Shipping V2 物流轨迹。 */ @PostMapping("/v2/tracking") @Operation(summary = "查询 Shipping V2 物流轨迹") @PreAuthorize("@ss.hasPermission('amazon:shipping:query')") public CommonResult<Map<String, Object>> getTrackingV2(@Valid @RequestBody ShippingRequestVO r) { return call(r, "getTracking", "GET", "/shipping/v2/tracking"); }
    /** 获取 Shipping V2 货件单据。 */ @PostMapping("/v2/shipments/documents") @Operation(summary = "获取 Shipping V2 货件单据") @PreAuthorize("@ss.hasPermission('amazon:shipping:query')") public CommonResult<Map<String, Object>> getShipmentDocuments(@Valid @RequestBody ShippingRequestVO r) { return call(r, "getShipmentDocuments", "GET", "/shipping/v2/shipments/{id}/documents"); }
    /** 取消 Shipping V2 货件。 */ @PostMapping("/v2/shipments/cancel") @Operation(summary = "取消 Shipping V2 货件") @PreAuthorize("@ss.hasPermission('amazon:shipping:update')") public CommonResult<Map<String, Object>> cancelShipmentV2(@Valid @RequestBody ShippingRequestVO r) { return call(r, "cancelShipment", "PUT", "/shipping/v2/shipments/{id}/cancel"); }
    /** 获取 Shipping V2 附加输入结构。 */ @PostMapping("/v2/shipments/additional-inputs") @Operation(summary = "获取 Shipping V2 附加输入结构") @PreAuthorize("@ss.hasPermission('amazon:shipping:query')") public CommonResult<Map<String, Object>> getAdditionalInputs(@Valid @RequestBody ShippingRequestVO r) { return call(r, "getAdditionalInputs", "GET", "/shipping/v2/shipments/additionalInputs/schema"); }
    /** 获取承运商账户表单字段。 */ @PostMapping("/v2/carrier-account-form-inputs") @Operation(summary = "获取承运商账户表单字段") @PreAuthorize("@ss.hasPermission('amazon:shipping:query')") public CommonResult<Map<String, Object>> getCarrierAccountFormInputs(@Valid @RequestBody ShippingRequestVO r) { return call(r, "getCarrierAccountFormInputs", "GET", "/shipping/v2/carrierAccountFormInputs"); }
    /** 查询承运商账户。 */ @PostMapping("/v2/carrier-accounts/list") @Operation(summary = "查询承运商账户") @PreAuthorize("@ss.hasPermission('amazon:shipping:query')") public CommonResult<Map<String, Object>> getCarrierAccounts(@Valid @RequestBody ShippingRequestVO r) { return call(r, "getCarrierAccounts", "PUT", "/shipping/v2/carrierAccounts"); }
    /** 创建或更新承运商账户。 */ @PostMapping("/v2/carrier-accounts") @Operation(summary = "创建承运商账户") @PreAuthorize("@ss.hasPermission('amazon:shipping:update')") public CommonResult<Map<String, Object>> linkCarrierAccountPut(@Valid @RequestBody ShippingRequestVO r) { return call(r, "linkCarrierAccount", "PUT", "/shipping/v2/carrierAccounts/{id}"); }
    /** 更新已连接的承运商账户。 */ @PostMapping("/v2/carrier-accounts/update") @Operation(summary = "更新承运商账户") @PreAuthorize("@ss.hasPermission('amazon:shipping:update')") public CommonResult<Map<String, Object>> linkCarrierAccountPost(@Valid @RequestBody ShippingRequestVO r) { return call(r, "linkCarrierAccount", "POST", "/shipping/v2/carrierAccounts/{id}"); }
    /** 解除承运商账户连接。 */ @PostMapping("/v2/carrier-accounts/unlink") @Operation(summary = "解除承运商账户连接") @PreAuthorize("@ss.hasPermission('amazon:shipping:update')") public CommonResult<Map<String, Object>> unlinkCarrierAccount(@Valid @RequestBody ShippingRequestVO r) { return call(r, "unlinkCarrierAccount", "PUT", "/shipping/v2/carrierAccounts/{id}/unlink"); }
    /** 生成集合单据。 */ @PostMapping("/v2/collection-forms") @Operation(summary = "生成集合单据") @PreAuthorize("@ss.hasPermission('amazon:shipping:create')") public CommonResult<Map<String, Object>> generateCollectionForm(@Valid @RequestBody ShippingRequestVO r) { return call(r, "generateCollectionForm", "POST", "/shipping/v2/collectionForms"); }
    /** 查询集合单据历史。 */ @PostMapping("/v2/collection-forms/history") @Operation(summary = "查询集合单据历史") @PreAuthorize("@ss.hasPermission('amazon:shipping:query')") public CommonResult<Map<String, Object>> getCollectionFormHistory(@Valid @RequestBody ShippingRequestVO r) { return call(r, "getCollectionFormHistory", "PUT", "/shipping/v2/collectionForms/history"); }
    /** 查询未清单货件。 */ @PostMapping("/v2/unmanifested-shipments") @Operation(summary = "查询未清单货件") @PreAuthorize("@ss.hasPermission('amazon:shipping:query')") public CommonResult<Map<String, Object>> getUnmanifestedShipments(@Valid @RequestBody ShippingRequestVO r) { return call(r, "getUnmanifestedShipments", "PUT", "/shipping/v2/unmanifestedShipments"); }
    /** 查询集合单据详情。 */ @PostMapping("/v2/collection-forms/detail") @Operation(summary = "查询集合单据详情") @PreAuthorize("@ss.hasPermission('amazon:shipping:query')") public CommonResult<Map<String, Object>> getCollectionForm(@Valid @RequestBody ShippingRequestVO r) { return call(r, "getCollectionForm", "GET", "/shipping/v2/collectionForms/{id}"); }
    /** 查询可用投递点。 */ @PostMapping("/v2/access-points") @Operation(summary = "查询可用投递点") @PreAuthorize("@ss.hasPermission('amazon:shipping:query')") public CommonResult<Map<String, Object>> getAccessPoints(@Valid @RequestBody ShippingRequestVO r) { return call(r, "getAccessPoints", "GET", "/shipping/v2/accessPoints"); }
    /** 提交无法投递反馈。 */ @PostMapping("/v2/ndr-feedback") @Operation(summary = "提交无法投递反馈") @PreAuthorize("@ss.hasPermission('amazon:shipping:update')") public CommonResult<Map<String, Object>> submitNdrFeedback(@Valid @RequestBody ShippingRequestVO r) { return call(r, "submitNdrFeedback", "POST", "/shipping/v2/ndrFeedback"); }
    /** 创建物流理赔。 */ @PostMapping("/v2/claims") @Operation(summary = "创建物流理赔") @PreAuthorize("@ss.hasPermission('amazon:shipping:create')") public CommonResult<Map<String, Object>> createClaim(@Valid @RequestBody ShippingRequestVO r) { return call(r, "createClaim", "POST", "/shipping/v2/claims"); }
    /** 将受校验的请求转交 Shipping Service。 */
    private CommonResult<Map<String, Object>> call(ShippingRequestVO request, String operation, String method, String path) { return CommonResult.success(shippingService.invoke(request, operation, method, path)); }
}
