### 查询商品评论主题
POST {{baseUrl}}/amazon/customer-feedback/items/review-topics
Authorization: Bearer {{token}}
Content-Type: application/json
tenant-id: {{adminTenantId}}

{"shopId":1,"countryCode":"US","asin":"B08N5WRWNW","sortBy":"MENTIONS"}

### 查询商品浏览节点
POST {{baseUrl}}/amazon/customer-feedback/items/browse-node
Authorization: Bearer {{token}}
Content-Type: application/json
tenant-id: {{adminTenantId}}

{"shopId":1,"countryCode":"US","asin":"B08N5WRWNW"}

### 查询浏览节点评论主题
POST {{baseUrl}}/amazon/customer-feedback/browse-nodes/review-topics
Authorization: Bearer {{token}}
Content-Type: application/json
tenant-id: {{adminTenantId}}

{"shopId":1,"countryCode":"US","browseNodeId":"283155","sortBy":"MENTIONS"}

### 查询商品评论趋势
POST {{baseUrl}}/amazon/customer-feedback/items/review-trends
Authorization: Bearer {{token}}
Content-Type: application/json
tenant-id: {{adminTenantId}}

{"shopId":1,"countryCode":"US","asin":"B08N5WRWNW"}

### 查询浏览节点评论趋势
POST {{baseUrl}}/amazon/customer-feedback/browse-nodes/review-trends
Authorization: Bearer {{token}}
Content-Type: application/json
tenant-id: {{adminTenantId}}

{"shopId":1,"countryCode":"US","browseNodeId":"283155"}

### 查询浏览节点退货主题
POST {{baseUrl}}/amazon/customer-feedback/browse-nodes/return-topics
Authorization: Bearer {{token}}
Content-Type: application/json
tenant-id: {{adminTenantId}}

{"shopId":1,"countryCode":"US","browseNodeId":"283155"}

### 查询浏览节点退货趋势
POST {{baseUrl}}/amazon/customer-feedback/browse-nodes/return-trends
Authorization: Bearer {{token}}
Content-Type: application/json
tenant-id: {{adminTenantId}}

{"shopId":1,"countryCode":"US","browseNodeId":"283155"}
